# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tiryD_j1UAaZlhyAsjV_LvmrCz5SNrR4
"""

!pip install streamlit

!pip install ngrok

import  streamlit as st
import joblib
import numpy as np

model=joblib.load('/content/churn_model.pk1')
# App title
st.title("Customer churn Prediction App")
st.markdown("Enter customer details below to predict the likelihood of churn.")
# User input sliders
total_charges=st.number_input("Total Charges (₹)", min_value=0.0,max_value=10000.0,value=2000.0)
monthly_charges=st.number_input("Monthly Charges (₹)",min_value=0.0,max_value=1000.0,value=100.0)
tenure=st.slider("Tenure (months)",min_value=0,max_value=72,value=12)

if st.button("predict churn"):
  input_data=np.array([[total_charges, monthly_charges, tenure]])
  prediction=model.predict(input_data)[0]

  if prediction ==1:
    st.error("customer is likely to churn")

  else:
    st.success("customer is likely to stay")







